### PR TITLE
Update to MC 1.12.1

### PR DESCRIPTION
**Pull request by Shadows-of-Fire**

### CODE REVIEW

**Comment by Kris1432** [comment]
wow, nice!

**Comment by CrazyPants** [comment]
Thank you. Sorry it has taken a while to merge.

**Comment by CrazyPants** [comment]
I have uploaded a build to curse. I have credited the release to you using your github user name. If you would like me to change that then just let me know.

**Comment by HenryLoenwind** [comment]
@Shadows-of-Fire could you have a look at #186, please? Did net/minecraft/world/biome/Biome.getBiomeName() become client-side only in 1.12?

Thx.

**Comment by Shadows-of-Fire** [comment]
I already did, see #187

**Comment by HenryLoenwind** [comment]
yeah, I just saw it. Sry, didn't notice that one because the order of project on my notification page keeps shifting around. Thx!

**Pull request merged**
