### PR TITLE
New: Dire Slime

### PR DESCRIPTION
**Pull request by HenryLoenwind**
A new type of slime that comes from dirt blocks being treated with a
wrong tool.

### CODE REVIEW

**Comment by tterrag1098** [comment]
Where do you register the entity?

**Comment by HenryLoenwind** [comment]
EnderZoo line 69:

    for (MobInfo mob : MobInfo.values()) { registerEntity(mob); }

**Comment by tterrag1098** [comment]
Ah right, ok.

**Comment by CrazyPants** [comment]
Had a quick look and I really like it.
The default damage + hp needs to be adjusted though. As it is, it is pretty hard to take any damage from them, even with no armor , and it is killed in 1 hit with wooden sword. 
I think the name will need to be changed too as it certainly isnt too 'dire' atm.

Let me know if you will make these changes, if not I will do a merge and make the changes myself soon.

**Comment by HenryLoenwind** [comment]
With damage/health I'm a bit conflicted. Yes, they should be hard, but on the other hand, players can (will) run into them early game. The values I set as default are the Magma Cube's ones:

small: h=3, a=3, chance=90%
medium: h=6, a=4, chance=8%
big: h=18, a=6, chance=2%

What'd be you suggestion for these? And, should I add config values for the size-chance, too?

The internal name actually is "i hate that DIREwulf20 is always breaking dirt with his pick, this SLIME is made to counter that", just a bit shortened ;). Any good suggestion for the localized name? I could only think of "dirt slime" (lame...).

**Comment by CrazyPants** [comment]
I see the issue with early game, but it will just force people to use a
wooded shovel if it is causing grief.

An option with the damage \health would be to adjust the values
significantly based on 'occupied time' of the chunk. I think I am only
using this when equipping random equipment on the fallen knights ATM.

One final option would be to track how many a player has caused to spawn
and increase the difficultly based on that.

Not sure if any of it is worth doing though. I will play around with
different values when I get a chance. Let me know what you think.

As for adding things to the config, I always add as much as possible, so
yes.

Thanks for the submission BTW. Great to get contributions.

**Comment by HenryLoenwind** [comment]
I can squish the commits if you want; I left them for now because it'll make it easier for you to see what I changed.

**Comment by CrazyPants** [comment]
I would prefer a single commit. I find it much easier to review
Thanks

**Comment by HenryLoenwind** [comment]
Squished. And added a custom model---like the magma cube but with 8 slices and exactly one block in size. All sizes are the same size, they only differ in their properties. The bigger ones just didn't look good with the oversized block texture on them, and they also tended to suffocate. The bigger (and more dangerous) ones will still sound differently.

Dire Slimes are fire-proof, after all they are made from dirt. (And I originally extended EntityMagmaCube to use its model. Could be changed with new model.)

There is one known bug: The hitbox rotates even though the rendered model does not.

**Comment by HenryLoenwind** [comment]
Any news on reviewing this?

**Comment by CrazyPants** [comment]
Sorry I haven't got to it. Should have some time in the next few days

**Pull request merged**
